/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.Cosmic;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 *
 * @author DeVeLoPer24
 */
public class FrmCosmic extends javax.swing.JFrame {

    /**
     * Creates new form FrmCosmic
     */
    public FrmCosmic() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("../img/icon.png")).getImage());
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtInputCosto = new javax.swing.JTextField();
        txtInputPF = new javax.swing.JTextField();
        txtInputKldc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCostoPuntoFuncion = new javax.swing.JTextField();
        txtCostoProyectoSW = new javax.swing.JTextField();
        txtDuracionProyecto = new javax.swing.JTextField();
        txtCostaraSoftware = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("METODO COSMIC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 310, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese Costo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, 30));

        jLabel3.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese PF");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, -1, 30));

        jLabel4.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese MLDC");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, -1, 30));

        txtInputCosto.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtInputCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputCostoKeyTyped(evt);
            }
        });
        getContentPane().add(txtInputCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 90, -1));

        txtInputPF.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtInputPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputPFKeyTyped(evt);
            }
        });
        getContentPane().add(txtInputPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 90, -1));

        txtInputKldc.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        txtInputKldc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputKldcKeyTyped(evt);
            }
        });
        getContentPane().add(txtInputKldc, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 110, 90, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Costo por Punto de Función");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, 30));

        jLabel6.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Costo del Proyecto del Software");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, -1, 30));

        jLabel7.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Duración del Proyecto");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, -1, 30));

        jLabel8.setFont(new java.awt.Font("Monospaced", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Costara el Software");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, 30));

        txtCostoPuntoFuncion.setEditable(false);
        txtCostoPuntoFuncion.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        getContentPane().add(txtCostoPuntoFuncion, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 120, -1));

        txtCostoProyectoSW.setEditable(false);
        txtCostoProyectoSW.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        getContentPane().add(txtCostoProyectoSW, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 120, -1));

        txtDuracionProyecto.setEditable(false);
        txtDuracionProyecto.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        getContentPane().add(txtDuracionProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 120, -1));

        txtCostaraSoftware.setEditable(false);
        txtCostaraSoftware.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        getContentPane().add(txtCostaraSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 330, 120, -1));

        jLabel9.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("BS");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, 30));

        btnCalcular.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculator_calc_6110.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        btnVolver.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel11.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("BS");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, 30));

        jLabel12.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Mes");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 290, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wooden board.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        double costo = Double.parseDouble(txtInputCosto.getText());
        double pf = Double.parseDouble(txtInputPF.getText());
        double kldc = Double.parseDouble(txtInputKldc.getText());
        Cosmic c = new Cosmic(costo,pf,kldc);
        double costoPuntoFuncion = c.CostoPuntoFuncion();
        double costoProyectoSoftware = c.CostoProyectoSoftware();
        double duracionProyecto = c.DuracionProyecto();
        double costaraSoftware = c.CostaraSoftware();
        
        txtCostoPuntoFuncion.setText(Math.round(costoPuntoFuncion * 100.0) / 100.0 + "");
        txtCostoProyectoSW.setText(Math.round(costoProyectoSoftware * 100.0) / 100.0 + "");
        txtDuracionProyecto.setText(Math.round(duracionProyecto * 100.0) / 100.0 + "");
        txtCostaraSoftware.setText(Math.round(costaraSoftware * 100.0) / 100.0 + "");
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmMenu frmMenu = new FrmMenu();
        frmMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtInputCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputCostoKeyTyped
        // TODO add your handling code here:
        numberDecimalKeyPress(evt, txtInputCosto);
    }//GEN-LAST:event_txtInputCostoKeyTyped

    private void txtInputPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputPFKeyTyped
        // TODO add your handling code here:
        numberDecimalKeyPress(evt, txtInputPF);
    }//GEN-LAST:event_txtInputPFKeyTyped

    private void txtInputKldcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputKldcKeyTyped
        // TODO add your handling code here:
        numberDecimalKeyPress(evt, txtInputKldc);
    }//GEN-LAST:event_txtInputKldcKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCosmic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCosmic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCosmic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCosmic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCosmic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCostaraSoftware;
    private javax.swing.JTextField txtCostoProyectoSW;
    private javax.swing.JTextField txtCostoPuntoFuncion;
    private javax.swing.JTextField txtDuracionProyecto;
    private javax.swing.JTextField txtInputCosto;
    private javax.swing.JTextField txtInputKldc;
    private javax.swing.JTextField txtInputPF;
    // End of variables declaration//GEN-END:variables

    public void numberDecimalKeyPress(KeyEvent evt, JTextField textField) {
    // declaramos una variable y le asignamos un evento
            char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && textField.getText().contains(".") && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        } else if ((car < '0' || car > '9') && (car != '.') && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }

}
