/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Models.LDC;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author DeVeLoPer24
 */
public class FrmLDC extends javax.swing.JFrame {

    /**
     * Creates new form FrmLDC
     */
    public FrmLDC() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("../img/icon.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtInputLDC = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtProductividad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCostoLDC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtEsfuerzo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Monospaced", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Método Lineas de Código LDC");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrese el Nro de LDC");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, 40));

        txtInputLDC.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        txtInputLDC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInputLDCKeyTyped(evt);
            }
        });
        getContentPane().add(txtInputLDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 120, -1));

        jLabel3.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Productividad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, 40));

        txtProductividad.setEditable(false);
        txtProductividad.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        getContentPane().add(txtProductividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 110, -1));

        jLabel4.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Costo por LDC");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, 40));

        txtCostoLDC.setEditable(false);
        txtCostoLDC.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        getContentPane().add(txtCostoLDC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 110, -1));

        jLabel5.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("LDC / MES");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 140, 40));

        jLabel6.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("$$/LDC");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, 40));

        btnCalcular.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnCalcular.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calculator_calc_6110.png"))); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.setContentAreaFilled(false);
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btnVolver.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(255, 255, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Esfuerzo");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, 40));

        txtEsfuerzo.setEditable(false);
        txtEsfuerzo.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        getContentPane().add(txtEsfuerzo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 110, -1));

        jLabel9.setFont(new java.awt.Font("Monospaced", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Costo");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, 40));

        txtCosto.setEditable(false);
        txtCosto.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 110, -1));

        jLabel10.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 255, 51));
        jLabel10.setText("Cocomo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/wooden board.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 410));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 470, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        double lineCode = Double.parseDouble(txtInputLDC.getText());
        
        LDC ldc = new LDC(lineCode);
        double esfuerzo = ldc.EstimacionEsfuerzo();
        double costo = ldc.EstimacionCosto();
        
        double productividad = ldc.EstimacionProductividad();
        double costo_ldc = ldc.CostoLDC();
        
        txtEsfuerzo.setText(Math.round(esfuerzo * 100.0) / 100.0 + "");
        txtCosto.setText(Math.round(costo * 100.0) / 100.0 + "");
        txtProductividad.setText(Math.round(productividad * 100.0) / 100.0 + "");
        txtCostoLDC.setText(Math.round(costo_ldc * 100.0) / 100.0 + "");
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        FrmMenu frmMenu = new FrmMenu();
        frmMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtInputLDCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInputLDCKeyTyped
        // TODO add your handling code here:
        numberKeyPress(evt);
    }//GEN-LAST:event_txtInputLDCKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLDC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLDC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtCostoLDC;
    private javax.swing.JTextField txtEsfuerzo;
    private javax.swing.JTextField txtInputLDC;
    private javax.swing.JTextField txtProductividad;
    // End of variables declaration//GEN-END:variables
    public void numberKeyPress(KeyEvent evt) {
    // declaramos una variable y le asignamos un evento
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car != (char) KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }
}
